### ISSUE TITLE
cannot import swift-2.0 into cocoapods

### ISSUE THREAD

**Issue by BluMist** [delba/JASON#1]
Seems to be lacking a podspec for the swift-2.0 tree?

**Comment by delba** [comment]
Thank you so much for the feedback @BluMist !

I added a podspec on `swift-2.0` and some [instructions](https://github.com/delba/JASON/tree/swift-2.0#cocoapods) to install JASON.

``` ruby
use_frameworks!

pod 'JASON', :git => 'https://github.com/delba/JASON.git', :branch => 'swift-2.0'
```

As soon as Swift 2.0 is released, you will be able to install JASON just by specifying the version.

Thanks!

**Comment by BluMist** [comment]
Confirm this works, thanks for the quick fix!
