### ISSUE TITLE
About the JSONKeys that if both model have the same properties like 'id'

### ISSUE THREAD

**Issue by arden** [delba/JASON#10]
About the JSONKeys that if both model have the same properties like 'id'
example:
struct User {
    var id = ""
}
struct Topic {
    var id = 0
}
the User model called id that is a String type
the Topic model called id that is a Int type.

now, where in JSONKeys how do define it.

**Comment by delba** [comment]
You can either **give a different name to the keys**:

``` swift
extension JSONKeys {
    static let stringID = JSONKey<String>("id")
    static let intID = JSONKey<Int>("id")
}
```

Or **define the keys within private extensions**:

``` swift
// User.swift

private extension JSONKeys {
    static let id = JSONKey<String>("id")
}

struct User {
    // ...
}
```

``` swift
// Topic.swift

private extension JSONKeys {
    static let id = JSONKey<Int>("id")
}

struct Topic {
    // ...
}
```

**Comment by arden** [comment]
thanks @delba
