### ISSUE TITLE
Extensions are not included in the pod sources

### ISSUE THREAD

**Issue by BluMist** [delba/JASON#25]
Did not see this mentioned in the README, is it the intention here for people to only pull the extensions they need? Wasn't expecting to have all the operators broken with the pod update.

**Comment by delba** [comment]
Yes, the extensions listed under the`Extensions` [directory](https://github.com/delba/JASON/tree/master/Extensions) aren't part of the main target anymore.
You'll have to drag and drop the files you want in you project.
