### ISSUE TITLE
The library isn't updated to Swift 3.0

### ISSUE THREAD

**Issue by kumarc-123** [delba/JASON#29]
Hi,

Can you please update this library to use latest Swift 3.0 standards?

**Comment by aymericio** [comment]
+1

**Comment by javikr** [comment]
+1, please update asap ;)

**Comment by AF-cgi** [comment]
+1

**Comment by delba** [comment]
Sorry guys, the lib was updated for swift 3.0 but didn't have a proper tag until tonight.

To install it with Carthage:

``` swift
github "delba/JASON" "~> 3.0"
```

I'm having some connectivity problems but the CocoaPod is coming soon :)

Thanks for your patience!
