### ISSUE TITLE
Can you push a new version to Cocoapods with Swift 2.0 integration?

### ISSUE THREAD

**Issue by mohamedmansour** [delba/JASON#3]
So I am trying to use this project in my "pod" and we cannot version the dependency, would be nice if we can make a new version, like 0.3 and host this.

**Comment by delba** [comment]
Hey @mohamedmansour, the `Swift-2.0` branch is now the `master` one and you can use JASON as a cocoa pod like this:

``` oggl
use_frameworks!

pod 'JASON', '~> 1.0'
```

> I'm trying to stick to semantic versioning, and so I had to bump straight to `1.0` :bowtie:

**Comment by mohamedmansour** [comment]
Awesome thanks @delba !
