### ISSUE TITLE
cant Parse JSON array of objects

### ISSUE THREAD

**Issue by Ramachandrajoshi** [delba/JASON#34]
i cant parse json array objects.

my json string is

 [{string:value,string:value},{string:value,string:value},{string:value,string:value},{string:value,string:value},{string:value,string:value},{string:value,string:value}]

how can i parse this type of strings?

**Comment by delba** [comment]
Please see the README

**Comment by Ramachandrajoshi** [comment]
Sorry, I'm new to ios &  swift. i didn't get this in README. can you put the code here please.

**Comment by delba** [comment]
I just pushed a new version (`v3.1`). It includes a new initializer that allows you to create a `JSON` struct from a JSON formatted string:

``` swift
public init(_ string: String?) {
    self.init(string?.data(using: String.Encoding.utf8))
}
```

Use it like this:

``` swift
let json = JSON(myString)
```

**Comment by Ramachandrajoshi** [comment]
thanks for quick update.
