### ISSUE TITLE
Argument labels do not match any available overloads

### ISSUE THREAD

**Issue by FogiDestructor** [delba/JASON#35]
Hi, I am currently converting an app from Swift 2 to Swift 3 and was wandering of replacing the existing JSON file with the JASON framework. Here's the issue that I get
![screen shot 2016-11-15 at 11 06 26 pm](https://cloud.githubusercontent.com/assets/23381963/20324300/b86a5f0c-ab88-11e6-8c78-5b5c679a1d35.png)

**Comment by delba** [comment]
Simply use `JSON(data)`. Let me know if it works!

**Comment by FogiDestructor** [comment]
Actually yes, but it gives the issue that the type 'JSON' is ambiguous without more context.

**Comment by delba** [comment]
You probably already have a `JSON` type defined. To remove the ambiguity, you can either use `JASON.JSON` explicitly or remove the other JSON framework
