### ISSUE TITLE
int64Value does not work on 32-bit architectures

### ISSUE THREAD

**Issue by Tarpsvo** [delba/JASON#37]
Since `NSNumber` is converted into `Int` before being made into `Int64`, the return value will be wrong on 32 bit architectures (happened on my iPod 5G for example).

(From `JASON+Properties.swift`)

**Comment by delba** [comment]
Hi @Tarpsvo, the `JASON+Properties.swift` isn't included by default in the framework and so, you remove the lines which cause issues when importing it by hand in you project.
