### ISSUE TITLE
any specific benefit to 1.1?

### ISSUE THREAD

**Issue by BluMist** [delba/JASON#4]
seems like those functionalities were already available, just now in subscript form?

**Comment by delba** [comment]
I haven't had time to update the REAME but it allows you to write things like this:

``` swift
extension JSONKeys {
    static let id = JSONKey<Int>("id")
    static let name = JSONKey<String?>("name")
}

class User {
    let id: Int
    var name: String?

    init(json: JSON) {
        id = json[.id]
        name = json[.name]
    }
}
```

This idea was borrowed (not to say stolen) from [SwiftyUserDefaults](https://github.com/radex/SwiftyUserDefaults) (see [article](http://radex.io/swift/nsuserdefaults/static/)).
