### ISSUE TITLE
JSONKeys这个设计感觉不合理

### ISSUE THREAD

**Issue by arden** [delba/JASON#9]
如果我有多个数据模型，比如：User，Topic等，但是这两个数据模型里都有name这个字段，但当这两个字段的数据类型等有区别的时候，JSONKeys怎么去定义它啊？

**Comment by delba** [comment]
你好 @arden ,

I'm not sure to understand. Could you please use English ?
Thanks!

**Comment by delba** [comment]
Closing due to lack of response.
